### ISSUE TITLE
Tenant support

### ISSUE THREAD

**Issue by braaar** [flexisoftorg/conf#72]
We want to add tenant support so that the app can be deployed to multiple tenants.

**Some key elements**
- Each tenant has their own database (with a unique IP address and port
- Each tenant can have their app hosted on a subdomain of flexisoft's domain or a domain of their own (e.g. `bjerk.flexisoftportal.no` or `inkasso.bjerk.io`)
- We want to configure everything in pulumi so that we can add new tenants by adding some values into a `yaml` file
- The `portal-api` and `portal-app` services must use environment variables wherever it is relevant so that they function across every tenant's own environment

**Comment by Xillians** [comment]
should api use same domain as the frontend?
example:
`inkasso.bjerk.io` -> `api.inkasso.bjerk.io` 

benefit of this is to only allow same domain to communicate between each other for security policies

**Comment by Xillians** [comment]
should api firebird values (host ip, port, database) be empty default values with a required .env value or should we set the hard coded values as default?

**Comment by simenandre** [comment]
> should api firebird values (host ip, port, database) be empty default values with a required .env value or should we set the hard coded values as default?

These values are already available in the customer data that is accessible as an environment value in production. I'm not sure it makes sense to default to anything, since there is no _default_ IMHO. 404 is probably enough?

**Comment by simenandre** [comment]
The tenant/customer object is available here:
https://github.com/flexisoftorg/conf/blob/a1fc4289887d8baec54c799ab660466ee6a44cb3/resources/get-customers.ts#L6-L15



> should api use same domain as the frontend? example: `inkasso.bjerk.io` -> `api.inkasso.bjerk.io`
> 
> benefit of this is to only allow same domain to communicate between each other for security policies

I have already setup so that `domain` (see above reference) is used for _portal_ and and `api.` is the API domain.

https://github.com/flexisoftorg/conf/blob/a1fc4289887d8baec54c799ab660466ee6a44cb3/resources/kubernetes/portal-app/portal-domains.ts#L43

See the configuration:
https://github.com/flexisoftorg/conf/blob/main/resources/kubernetes/portal-app/portal-domains.ts

**Comment by simenandre** [comment]
Customer data is added to Sanity; see the [studio repository](https://github.com/flexisoftorg/studio).
